### ISSUE TITLE
如何绘制0.5px的边框

### ISSUE THREAD

**Issue by Zendq1998** [Zendq1998/blog#5]
### 基本概念
- 设备像素（物理像素）device pixel
代表显示屏中最小的物理单位
- css 像素
浏览器使用的抽象单元，也称为设备无关像素 DIP
- 设备像素比 devicePixelRatio
window.devicePixelRatio 可以获取当前屏幕的该值
设备像素/css像素。值为 1 的屏幕称之为标准屏；目前，大部分移动设备都是高清屏，即 devicePixelRatio 值大于 1 的屏幕，对于苹果设备来说，我们经常听到 Retina 视网膜屏，其中 iPhone6/6s/7 的 devicePixelRatio 值为 2；而 iPhone6 plus/6s plus/7 plus 的 devicePixelRatio 值为 3。

#### 正常思路
我们希望画一条物理像素为 1px 的边框，在设备像素比为2的情况下，css像素是0.5px，设备像素比为3时，css像素是0.33px。

```css
.border {
    border-width: 1px;
}
@media only screen and (min-device-pixel-ratio: 2) {
    .border {
        border-width: 0.5px;
    }
}
@media only screen and (min-device-pixel-ratio: 3) {
    .border {
        border-width: 0.33px;
    }
}
```

但是，chrome 浏览器会把 border-width 四舍五入，0.5px 当作 1px，0.33px 当作 0。

#### 解决方法（ devicePixelRatio=2 ）
主要思路：利用伪元素和 transform 解决

```css
code {
    font-size: 14px;
    height: 20px;
    line-height: 20px;
    border-radius: 4px;
    display: inline-block;
    vertical-align: middle;
    padding: 0 4px;
    margin: 0 2px;
    position: relative;
    top: -2px;
    background-color: #f6f7f9;
    color: #373c43;
    position: relative;
  }
code:before {
    content: '';
    position: absolute;
    box-sizing: border-box;
    width: 200%;
    height: 200%;
    border: 1px solid #e4e5e7;
    border-radius: 8px;
    transform: scale(.5);
    left: -50%;
    top: -50%;
}
```

也可以写成 mixin，利于代码复用
```css
  .thin-border (@color: #e4e5e7, @radius: 4px) {
    position: relative;
    &::before {
      content: '';
      position: absolute;
      box-sizing: border-box;
      width: 200%;
      height: 200%;
      border: 1px solid @color;
      border-radius: @radius * 2;
      transform: scale(.5);
      left: -50%;
      top: -50%;
    }
  }
...
    code {
      .thin-border(#e4e5e7, 4px);
      font-size: 14px;
      height: 20px;
      line-height: 20px;
      display: inline-block;
      vertical-align: middle;
      padding: 0 4px;
      margin: 0 2px;
      top: -2px;
      background-color: #f6f7f9;
      color: #373c43;
    }
```
效果

![0.5px实现](https://ws1.sinaimg.cn/large/006GC8NZgy1g5w0qq7bv4j30px03ewet.jpg)
![原样式](https://ws1.sinaimg.cn/large/006GC8NZgy1g5w0qq6b05j30o802wjro.jpg)

### 参考链接
[Retina屏的移动设备如何实现真正1px的线？](https://jinlong.github.io/2015/05/24/css-retina-hairlines/)
[高清屏一像素边框问题](http://objcer.com/2017/06/19/one-pixel-border/)
https://github.com/youzan/vant/blob/dev/src/style/mixins/hairline.less
https://github.com/didi/cube-ui/blob/dev/src/common/stylus/mixin.styl
